# read the file into R
```{r}
file <- read.csv("/Users/irenecho/Desktop/final.csv", header = T)
head(file)
```

# set v2 to years column
```{r}
file$V2 <- substr(file$V2, 1,nchar(file$V2)-4)
file$V2 <- as.numeric(file$V2)
head(file)
```

# change column names
```{r}
colnames(file) <- c('station_id', 'year', 'TOBS', 'TMAX', 'TMIN', 'PRCP', 'SNOW', 'SNWD', 'totalMean')
head(file)
```

# create prev_temp
```{r}
fun_converter <- function(x) {
  new_file = unique(x[c('year', 'totalMean')])
  print(new_file)
  # print(typeof(new_file[0,1]))
  # print((new_file[new_file[1] == 2000-1])[2])
  # x$prev_temp <- apply(x, 1, FUN = function(x) print(as.numeric(x[2])-1))
  x$prev_temp <- apply(x, 1, FUN = function(x) new_file[new_file[1] == (as.numeric(x[2])-1)][2])
  return(x)
  print(x$prev_temp)
  
}
file = fun_converter(file)
```

# binary: find if the temperature has risen compare to the last year [TOBS, TMAX, TMIN]
```{r}
file <- na.omit(file)

file$TOBS_is_overheated = ifelse(file$TOBS> file$prev_temp, 1, 0)

file$TMAX_is_overheated = ifelse(file$TMAX> file$prev_temp, 1, 0)

file$TMIN_is_overheated = ifelse(file$TMIN> file$prev_temp, 1, 0)
```

```{r}
head(file)
```

