universe = vanilla
log = log/project_$(file)_$(Process).log
error = error/project_$(file)_$(Process).err
output = output/project_$(file)_$(Process).out

executable = ./process.sh

arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ./$(file).gz, http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, process.R, packages.tar.gz

request_cpus = 1
request_memory = 2GB
request_disk = 2GB

queue file from inputFileNames
